package com.portscanner.report;

import com.portscanner.model.OsGuess;
import com.portscanner.model.PortStatus;
import com.portscanner.model.ScanReport;
import com.portscanner.model.ScanResult;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDateTime;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class MetasploitRcExporterTest {

    @TempDir
    Path tempDir;

    private ScanReport buildReport() {
        ScanResult r22 = ScanResult.builder()
                .port(22).status(PortStatus.OPEN).serviceName("SSH").responseTimeMs(5).build();
        ScanResult r80 = ScanResult.builder()
                .port(80).status(PortStatus.OPEN).serviceName("HTTP").responseTimeMs(10).build();
        ScanResult r3306 = ScanResult.builder()
                .port(3306).status(PortStatus.OPEN).serviceName("MySQL").responseTimeMs(8).build();
        return ScanReport.builder()
                .host("target.example.com")
                .resolvedIp("10.0.0.1")
                .scannedAt(LocalDateTime.of(2026, 3, 15, 9, 0, 0))
                .durationMs(2000)
                .totalScanned(1024)
                .openCount(3)
                .filteredCount(0)
                .openPorts(List.of(r22, r80, r3306))
                .filteredPorts(List.of())
                .build();
    }

    @Test
    void exports_valid_rc_file() throws Exception {
        Path out = tempDir.resolve("scan.rc");
        new MetasploitRcExporter().export(buildReport(), out);
        assertTrue(Files.exists(out));
        String content = Files.readString(out, StandardCharsets.UTF_8);
        assertFalse(content.isBlank());
    }

    @Test
    void contains_header_comment() throws Exception {
        Path out = tempDir.resolve("scan.rc");
        new MetasploitRcExporter().export(buildReport(), out);
        String content = Files.readString(out, StandardCharsets.UTF_8);
        assertTrue(content.contains("# Metasploit resource script generated by port-scanner"));
        assertTrue(content.contains("target.example.com"));
    }

    @Test
    void contains_usage_with_filename() throws Exception {
        Path out = tempDir.resolve("myscan.rc");
        new MetasploitRcExporter().export(buildReport(), out);
        String content = Files.readString(out, StandardCharsets.UTF_8);
        assertTrue(content.contains("msfconsole -r myscan.rc"));
    }

    @Test
    void contains_workspace_command() throws Exception {
        Path out = tempDir.resolve("scan.rc");
        new MetasploitRcExporter().export(buildReport(), out);
        String content = Files.readString(out, StandardCharsets.UTF_8);
        assertTrue(content.contains("workspace -a portscanner"));
    }

    @Test
    void registers_host_ip() throws Exception {
        Path out = tempDir.resolve("scan.rc");
        new MetasploitRcExporter().export(buildReport(), out);
        String content = Files.readString(out, StandardCharsets.UTF_8);
        assertTrue(content.contains("hosts -a 10.0.0.1"));
    }

    @Test
    void registers_services_for_open_ports() throws Exception {
        Path out = tempDir.resolve("scan.rc");
        new MetasploitRcExporter().export(buildReport(), out);
        String content = Files.readString(out, StandardCharsets.UTF_8);
        assertTrue(content.contains("services -a -p 22"));
        assertTrue(content.contains("services -a -p 80"));
        assertTrue(content.contains("services -a -p 3306"));
    }

    @Test
    void contains_tcp_portscan_module() throws Exception {
        Path out = tempDir.resolve("scan.rc");
        new MetasploitRcExporter().export(buildReport(), out);
        String content = Files.readString(out, StandardCharsets.UTF_8);
        assertTrue(content.contains("use auxiliary/scanner/portscan/tcp"));
        assertTrue(content.contains("set RHOSTS 10.0.0.1"));
    }

    @Test
    void suggests_ssh_module_for_port_22() throws Exception {
        Path out = tempDir.resolve("scan.rc");
        new MetasploitRcExporter().export(buildReport(), out);
        String content = Files.readString(out, StandardCharsets.UTF_8);
        assertTrue(content.contains("auxiliary/scanner/ssh/ssh_version"));
    }

    @Test
    void suggests_http_module_for_port_80() throws Exception {
        Path out = tempDir.resolve("scan.rc");
        new MetasploitRcExporter().export(buildReport(), out);
        String content = Files.readString(out, StandardCharsets.UTF_8);
        assertTrue(content.contains("auxiliary/scanner/http/http_version"));
    }

    @Test
    void suggests_mysql_module_for_port_3306() throws Exception {
        Path out = tempDir.resolve("scan.rc");
        new MetasploitRcExporter().export(buildReport(), out);
        String content = Files.readString(out, StandardCharsets.UTF_8);
        assertTrue(content.contains("auxiliary/scanner/mysql/mysql_version"));
    }

    @Test
    void os_guess_written_when_present() throws Exception {
        ScanReport report = buildReport().toBuilder()
                .osGuess(OsGuess.builder().os("Windows Server 2019").confidence("high").method("rdp").build())
                .build();
        Path out = tempDir.resolve("scan.rc");
        new MetasploitRcExporter().export(report, out);
        String content = Files.readString(out, StandardCharsets.UTF_8);
        assertTrue(content.contains("hosts -u 10.0.0.1"));
        assertTrue(content.contains("Windows Server 2019"));
    }

    @Test
    void no_suggestions_section_when_no_known_ports() throws Exception {
        ScanResult r9999 = ScanResult.builder()
                .port(9999).status(PortStatus.OPEN).serviceName("Unknown").build();
        ScanReport report = ScanReport.builder()
                .host("192.168.1.1")
                .resolvedIp("192.168.1.1")
                .durationMs(100)
                .totalScanned(10)
                .openCount(1)
                .filteredCount(0)
                .openPorts(List.of(r9999))
                .filteredPorts(List.of())
                .build();
        Path out = tempDir.resolve("scan.rc");
        new MetasploitRcExporter().export(report, out);
        String content = Files.readString(out, StandardCharsets.UTF_8);
        assertFalse(content.contains("Suggested modules"));
    }

    @Test
    void rc_extension_selects_metasploit_exporter() {
        var exporter = ExporterFactory.getExporter("output.rc", null);
        assertInstanceOf(MetasploitRcExporter.class, exporter);
    }

    @Test
    void format_msf_selects_metasploit_exporter() {
        var exporter = ExporterFactory.getExporter("output.txt", "msf", null);
        assertInstanceOf(MetasploitRcExporter.class, exporter);
    }

    @Test
    void format_metasploit_selects_metasploit_exporter() {
        var exporter = ExporterFactory.getExporter("output.txt", "metasploit", null);
        assertInstanceOf(MetasploitRcExporter.class, exporter);
    }
}
