package com.portscanner.report;

import com.portscanner.model.ScanReport;
import com.portscanner.model.ScanResult;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Exports a {@link ScanReport} as a Metasploit Framework resource script ({@code .rc}).
 *
 * <p>The generated script can be loaded with:
 * <pre>
 *   msfconsole -r scan.rc
 * </pre>
 *
 * <p>It populates the Metasploit database with host and service records, then
 * provides an optional TCP verification scan using {@code auxiliary/scanner/portscan/tcp}.
 */
public class MetasploitRcExporter implements ReportExporter {

    private static final DateTimeFormatter DT = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    @Override
    public void export(ScanReport report, Path outputPath) throws IOException {
        Files.writeString(outputPath, buildScript(report, outputPath.getFileName().toString()), StandardCharsets.UTF_8);
    }

    private static String buildScript(ScanReport report, String filename) {
        StringBuilder sb = new StringBuilder();
        String ip = report.getResolvedIp() != null ? report.getResolvedIp() : report.getHost();
        List<ScanResult> open = report.getOpenPorts() != null ? report.getOpenPorts() : List.of();
        String portList = open.stream()
                .map(r -> String.valueOf(r.getPort()))
                .collect(Collectors.joining(","));

        // ── Header ────────────────────────────────────────────────────────────
        sb.append("# Metasploit resource script generated by port-scanner\n");
        sb.append("# Host:     ").append(report.getHost()).append("\n");
        if (report.getResolvedIp() != null && !report.getResolvedIp().equals(report.getHost())) {
            sb.append("# IP:       ").append(ip).append("\n");
        }
        if (report.getScannedAt() != null) {
            sb.append("# Scanned:  ").append(report.getScannedAt().format(DT)).append("\n");
        }
        sb.append(String.format("# Results:  %d open, %d filtered, %d scanned (%.2fs)%n",
                report.getOpenCount(), report.getFilteredCount(), report.getTotalScanned(),
                report.getDurationMs() / 1000.0));
        sb.append("#\n");
        sb.append("# Usage: msfconsole -r ").append(filename).append("\n\n");

        // ── Workspace setup ───────────────────────────────────────────────────
        sb.append("# Create / switch to a dedicated workspace\n");
        sb.append("workspace -a portscanner\n\n");

        // ── Register host ─────────────────────────────────────────────────────
        sb.append("# Register the scanned host\n");
        sb.append("hosts -a ").append(ip).append("\n");
        if (report.getOsGuess() != null) {
            sb.append("hosts -u ").append(ip)
              .append(" -o \"").append(report.getOsGuess().getOs()).append("\"\n");
        }
        sb.append("\n");

        // ── Register services ─────────────────────────────────────────────────
        if (!open.isEmpty()) {
            sb.append("# Register discovered services\n");
            for (ScanResult r : open) {
                String svc = r.getServiceName() != null
                        ? r.getServiceName().toLowerCase().replaceAll("[^a-z0-9_-]", "") : "unknown";
                sb.append(String.format("services -a -p %d -t tcp -n %s -s open %s%n",
                        r.getPort(), svc, ip));
            }
            sb.append("\n");
        }

        // ── Verify with TCP portscan module ───────────────────────────────────
        if (!portList.isEmpty()) {
            sb.append("# Verify open ports with Metasploit TCP scanner\n");
            sb.append("use auxiliary/scanner/portscan/tcp\n");
            sb.append("set RHOSTS ").append(ip).append("\n");
            sb.append("set PORTS ").append(portList).append("\n");
            sb.append("set THREADS 10\n");
            sb.append("run\n\n");
        }

        // ── Suggested modules ──────────────────────────────────────────────────
        appendSuggestedModules(sb, open, ip);

        sb.append("# End of resource script\n");
        return sb.toString();
    }

    /** Appends suggested Metasploit modules based on discovered services. */
    private static void appendSuggestedModules(StringBuilder sb, List<ScanResult> open, String ip) {
        boolean hasSuggestions = false;
        for (ScanResult r : open) {
            String svc = r.getServiceName() != null ? r.getServiceName().toLowerCase() : "";
            String module = suggestModule(r.getPort(), svc);
            if (module != null) {
                if (!hasSuggestions) {
                    sb.append("# Suggested modules based on discovered services\n");
                    sb.append("# (uncomment to run)\n");
                    hasSuggestions = true;
                }
                sb.append("# use ").append(module).append("\n");
                sb.append("# set RHOSTS ").append(ip).append("\n");
                sb.append("# run\n");
            }
        }
        if (hasSuggestions) sb.append("\n");
    }

    private static String suggestModule(int port, String svc) {
        if (port == 21  || svc.contains("ftp"))    return "auxiliary/scanner/ftp/ftp_version";
        if (port == 22  || svc.contains("ssh"))    return "auxiliary/scanner/ssh/ssh_version";
        if (port == 23  || svc.contains("telnet")) return "auxiliary/scanner/telnet/telnet_version";
        if (port == 25  || svc.contains("smtp"))   return "auxiliary/scanner/smtp/smtp_version";
        if (port == 80  || port == 8080)            return "auxiliary/scanner/http/http_version";
        if (port == 443 || port == 8443)            return "auxiliary/scanner/http/ssl_version";
        if (port == 445 || svc.contains("smb"))    return "auxiliary/scanner/smb/smb_version";
        if (port == 3306 || svc.contains("mysql")) return "auxiliary/scanner/mysql/mysql_version";
        if (port == 5432 || svc.contains("postgres")) return "auxiliary/scanner/postgres/postgres_version";
        if (port == 3389 || svc.contains("rdp"))   return "auxiliary/scanner/rdp/rdp_scanner";
        if (port == 27017 || svc.contains("mongo")) return "auxiliary/scanner/mongodb/mongodb_login";
        if (port == 6379 || svc.contains("redis")) return "auxiliary/scanner/redis/redis_server";
        return null;
    }
}
