Args = --no-fallback \
       -H:+ReportExceptionStackTraces \
       --enable-url-protocols=https,http \
       --initialize-at-run-time=ch.qos.logback \
       --initialize-at-run-time=com.googlecode.lanterna \
       --initialize-at-run-time=net.java.dev.jna \
       --initialize-at-run-time=net.java.dev.jna.platform \
       --initialize-at-run-time=org.xerial.sqlite \
       --initialize-at-run-time=org.jline \
       -H:ReflectionConfigurationFiles=${.}/reflect-config.json \
       -H:ResourceConfigurationFiles=${.}/resource-config.json \
       -H:JNIConfigurationFiles=${.}/jni-config.json \
       -H:DynamicProxyConfigurationFiles=${.}/proxy-config.json
